import 'package:tastynav_cuisines/model/meal.dart';

import './model/category.dart';
import 'package:flutter/material.dart';

const DUMMY_CATEGORIES = const [
  Category(id: 'c1', title: 'Italian', color: Colors.purple),
  Category(id: 'c2', title: 'Quick & Easy', color: Colors.red),
  Category(id: 'c3', title: 'Hamburgers', color: Colors.orange),
  Category(id: 'c4', title: 'German', color: Colors.amber),
  Category(id: 'c5', title: 'Light & Lovely', color: Colors.blue),
  Category(id: 'c6', title: 'Exotic', color: Colors.green),
  Category(id: 'c7', title: 'Breakfast', color: Colors.lightBlue),
  Category(id: 'c8', title: 'Asian', color: Colors.lightGreen),
  Category(id: 'c9', title: 'French', color: Colors.pink),
  Category(id: 'c10', title: 'Summer', color: Colors.teal),
];

 final DUMMY_MEALS =  [
  Meal(
    id: '1',
    title: 'Spaghetti with Tomato Sauce',
    imageUrl:
        'https://images.archanaskitchen.com/images/recipes/world-recipes/pasta-recipes/Spaghetti_Pasta_Recipe_In_Creamy_Tomato_Sauce_Kids_Recipes_Made_With_Del_Monte_3_d6522012db.jpg',
    categories: ['c1', 'c2'],
    indgredients: [
      '4 Tomatoes',
      '1 Tablespoon of Olive Oil',
      '1 Onion',
      '250g Spaghetti',
      'Spices',
      'Cheese (optional)',
    ],
    steps: [
      'Cut the tomatoes and the onion into small pieces.',
      'Boil some water - add salt to it once it boils.',
      'Put the spaghetti into the boiling water - they should be done in about 10 to 12 minutes.',
      'In the meantime, heaten up some olive oil and add the cut onion.',
      'After 2 minutes, add the tomato pieces, salt, pepper and your other spices.',
      'The sauce will be done once the spaghetti are.',
      'Feel free to add some cheese on top of the finished dish.',
    ],
    duration: 20,
    complexity: Complexity.Simple,
    affordability: Affordability.Affordable,
    isGlutenFree: false,
    isVegan: false,
    isLactoseFree: false,
    isVegetarian: false,
    isFavourite: false,
  ),
  Meal(

    id: '2',
    title: 'Toast Hawaii',
    imageUrl:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTuPwsGjXYf1m1cwA5gkHFv5c_muSbNyPvuA&s',
    categories: ['c2', 'c7'],
    indgredients: [
      '1 Slice White Bread',
      '1 Slice Ham',
      '1 Slice Pineapple',
      '1-2 Slices of Cheese',
      'Butter',
    ],
    steps: [
      'Butter one side of the white bread',
      'Layer ham, the pineapple and cheese on the white bread',
      'Bake the toast for around 10 minutes in the oven at 200°C',
    ],
    duration: 10,
    complexity: Complexity.Simple,
    affordability: Affordability.Affordable,
    isGlutenFree: false,
    isVegan: false,
    isLactoseFree: false,
    isVegetarian: false,
    isFavourite: false,
  ),

  Meal(

    id: '3',
    title: 'Classic Hamburger',
    imageUrl:
        'https://assets.biggreenegg.eu/app/uploads/2019/03/28145521/topimage-classic-hamburger-2019m04-800x534.jpg',
    categories: ['c3'],
    indgredients: [
      '300g Cattle Hack',
      '1 Tomato',
      '1 Cucumber',
      '1 Onion',
      'Ketchup',
      '2 Burger Buns',
    ],
    steps: [
      'Form 2 patties',
      'Fry the patties for c. 4 minutes on each side',
      'Quickly fry the buns for c. 1 minute on each side',
      'Bruch buns with ketchup',
      'Serve burger with tomato, cucumber and onion',
    ],
    duration: 20,
    complexity: Complexity.Simple,
    affordability: Affordability.Affordable,
    isGlutenFree: false,
    isVegan: false,
    isLactoseFree: false,
    isVegetarian: false,
    isFavourite: false,
  ),

  Meal(

    id: '4',
    title: 'Wiener Schnitzel',
    imageUrl:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSmmMc6Ee_YMsGLID8FB2hkEuvzRofcVl6M9Q&s',
    categories: ['c4'],
    indgredients: [
      '8 Veal Cutlets',
      '4 Eggs',
      '200g Bread Crumbs',
      '100g Flour',
      '300ml Butter',
      '100g Vegetable Oil',
      'Salt',
      'Lemon Slices',
    ],
    steps: [
      'Tenderize the veal to about 2–4mm, and salt on both sides.',
      'On a flat plate, stir the eggs briefly with a fork.',
      'Lightly coat the cutlets in flour then dip into the egg, and finally, coat in breadcrumbs.',
      'Heat the butter and oil in a large pan (let the fat get very hot) and fry the schnitzels until golden brown on both sides.',
      'Make sure to toss the pan regularly so that the schnitzels are surrounded by oil and the crumbing becomes ‘fluffy’.',
      'Remove, and drain on kitchen paper. Fry the parsley in the remaining oil and drain.',
      'Place the schnitzels on awarmed plate and serve garnished with parsley and slices of lemon.',
    ],
    duration: 60,
    complexity: Complexity.Challenging,
    affordability: Affordability.Luxurious,
    isGlutenFree: false,
    isVegan: false,
    isLactoseFree: false,
    isVegetarian: false,
    isFavourite: false,
  ),
  Meal(
    id: '5',
    title: 'Salad with Smoked Salmon',
    imageUrl:
        'https://www.acouplecooks.com/wp-content/uploads/2021/07/Smoked-Salmon-Salad-010s.jpg',
    categories: ['c5', 'c6', 'c10'],
    indgredients: [
      'Arugula',
      'Lamb\'s Lettuce',
      'Parsley',
      'Fennel',
      '200g Smoked Salmon',
      'Mustard',
      'Balsamic Vinegar',
      'Olive Oil',
      'Salt and Pepper',
    ],
    steps: [
      'Wash and prepare the salad greens.',
      'Slice the smoked salmon into bite-sized pieces.',
      'Mix mustard, balsamic vinegar, olive oil, salt, and pepper to make the dressing.',
      'Toss the salad greens with the dressing.',
      'Top the salad with smoked salmon pieces.',
    ],
    duration: 15,
    complexity: Complexity.Simple,
    affordability: Affordability.Affordable,
    isGlutenFree: true,
    isVegan: false,
    isLactoseFree: false,
    isVegetarian: false,
    isFavourite: false,
  ),

  Meal(
    id: '6',
    title: 'Delicious Orange Mousse',
    imageUrl:
        'https://www.abakingjourney.com/wp-content/uploads/2023/07/Chocolate-Orange-Mousse-2.jpg',
    categories: ['c5', 'c6', 'c10'],
    indgredients: [
      'Arugula',
      'Lamb\'s Lettuce',
      'Parsley',
      'Fennel',
      '200g Smoked Salmon',
      'Mustard',
      'Balsamic Vinegar',
      'Olive Oil',
      'Salt and Pepper',
    ],
    steps: [
      'Wash and prepare the salad greens.',
      'Slice the smoked salmon into bite-sized pieces.',
      'Mix mustard, balsamic vinegar, olive oil, salt, and pepper to make the dressing.',
      'Toss the salad greens with the dressing.',
      'Top the salad with smoked salmon pieces.',
    ],
    duration: 15,
    complexity: Complexity.Simple,
    affordability: Affordability.Affordable,
    isGlutenFree: true,
    isVegan: false,
    isLactoseFree: false,
    isVegetarian: false,
    isFavourite: false,
  ),

  Meal(
    id: '7',
    title: 'Pancakes',
    imageUrl:
        'https://www.inspiredtaste.net/wp-content/uploads/2025/07/Pancake-Recipe-1.jpg',
    categories: ['c4'],
    indgredients: [
      '8 Veal Cutlets',
      '4 Eggs',
      '200g Bread Crumbs',
      '100g Flour',
      '300ml Butter',
      '100g Vegetable Oil',
      'Salt',
      'Lemon Slices',
    ],
    steps: [
      'Tenderize the veal to about 2–4mm, and salt on both sides.',
      'On a flat plate, stir the eggs briefly with a fork.',
      'Lightly coat the cutlets in flour then dip into the egg, and finally, coat in breadcrumbs.',
      'Heat the butter and oil in a large pan (let the fat get very hot) and fry the schnitzels until golden brown on both sides.',
      'Make sure to toss the pan regularly so that the schnitzels are surrounded by oil and the crumbing becomes ‘fluffy’.',
      'Remove, and drain on kitchen paper. Fry the parsley in the remaining oil and drain.',
      'Place the schnitzels on awarmed plate and serve garnished with parsley and slices of lemon.',
    ],
    duration: 60,
    complexity: Complexity.Challenging,
    affordability: Affordability.Luxurious,
    isGlutenFree: false,
    isVegan: false,
    isLactoseFree: false,
    isVegetarian: false,
    isFavourite: false,
  ),

  Meal(
    id: '8',
    title: 'Creamy Indian Chicken Curry',
    imageUrl:
        'https://images.immediate.co.uk/production/volatile/sites/30/2023/12/Creamy-tofu-curry-with-homemade-roti-5f35ec0.jpg',
    categories: ['c2', 'c8'],
    indgredients: [
      '4 Chicken Breasts',
      '1 Onion',
      '2 Cloves of Garlic',
      '1 Piece of Ginger',
      '4 Tablespoons Almonds',
      '1 Teaspoon Cayenne Pepper',
      '500ml Coconut Milk',
    ],
    steps: [
      'Cut the chicken breasts into bite-sized pieces.',
      'Chop the onion, garlic, and ginger.',
      'Toast the almonds in a dry pan until golden.',
      'Sauté the onion, garlic, and ginger until fragrant.',
      'Add the chicken pieces and cook until browned.',
      'Stir in the cayenne pepper and toasted almonds.',
      'Pour in the coconut milk and simmer until the chicken is cooked through.',
    ],
    duration: 45,
    complexity: Complexity.Challenging,
    affordability: Affordability.Luxurious,
    isGlutenFree: true,
    isVegan: false,
    isLactoseFree: false,
    isVegetarian: false,
    isFavourite: false,
  ),

  Meal(
    id: '9',
    title: 'Chocolate Souffle',
    imageUrl:
        'https://img.taste.com.au/rzQh6Xgx/taste/2016/11/easy-molten-chocolate-souffle-58756-1.jpeg',
    categories: ['c5', 'c9', 'c10'],
    indgredients: [
      '1 Teaspoon melted Butter',
      '2 Tablespoons white Sugar',
      '2 Ounces 70% dark Chocolate, broken into pieces',
    ],
    steps: [
      'Preheat oven to 190°C. Line a rimmed baking sheet with parchment paper.',
      'Brush bottom and sides of 2 ramekins with melted butter; cover bottom and sides right up to the rim.',
      'Add 1 tablespoon white sugar to ramekins. Rotate ramekins until sugar coats all surfaces.',
      'Place chocolate pieces in a metal mixing bowl.',
      'Place bowl over a pan of about 3 cups hot water over low heat.',
      'Melt chocolate while stirring occasionally.',
    ],
    duration: 45,
    complexity: Complexity.Challenging,
    affordability: Affordability.Luxurious,
    isGlutenFree: false,
    isVegan: false,
    isLactoseFree: false,
    isVegetarian: false,
    isFavourite: false,
  ),

  Meal(
    id: '10',
    title: 'Asparagus Salad with Cherry Tomatoes',
    imageUrl:
        'https://i.ytimg.com/vi/JfwXsiUJy6Q/maxresdefault.jpg',
    categories: ['c1', 'c5', 'c10'],
    indgredients: [
      'White and Green Asparagus',
      '30g Pine Nuts',
      '300g Cherry Tomatoes',
      'Salad',
      'Salt, Pepper and Olive Oil',
    ],
    steps: [
      'Wash and trim the asparagus.',
      'Blanch the asparagus in boiling water for 2-3 minutes, then plunge into ice water.',
      'Toast the pine nuts in a dry pan until golden.',
      'Halve the cherry tomatoes.',
      'Arrange the asparagus, pine nuts, and cherry tomatoes on a plate.',
      'Drizzle with olive oil and season with salt and pepper.',
      'Serve with a side of fresh salad leaves.',
    ],
    duration: 20,
    complexity: Complexity.Simple,
    affordability: Affordability.Affordable,
    isGlutenFree: true,
    isVegan: true,
    isLactoseFree: true,
    isVegetarian: true,
    isFavourite: false,
  ),

  Meal(
    id: '11',
    title: 'Fruit Smoothie',
    imageUrl:
        'https://lilluna.com/wp-content/uploads/2022/10/fruit-smoothie-resize-14.jpg',
    categories: ['c5', 'c6', 'c10'],
    indgredients: [
      '1 Banana',
      '1 Cup Mixed Berries',
      '1/2 Cup Yogurt',
      '1/2 Cup Orange Juice',
      '1 Tablespoon Honey',
    ],
    steps: [
      'Peel the banana and break it into chunks.',
      'Add the banana, mixed berries, yogurt, orange juice, and honey to a blender.',
      'Blend until smooth.',
      'Pour into a glass and serve immediately.',
    ],
    duration: 10,
    complexity: Complexity.Simple,
    affordability: Affordability.Affordable,
    isGlutenFree: true,
    isVegan: true,
    isLactoseFree: true,
    isVegetarian: true,
    isFavourite: false,
  ),

  Meal(
    id: '12',
    title: 'Grilled Chicken Salad',
    imageUrl:
        'https://www.licious.in/blog/wp-content/uploads/2020/12/Grilled-Chicken-Salad-min.jpg',
    categories: ['c5', 'c6', 'c10'],
    indgredients: [
      '200g Grilled Chicken Breast',
      'Mixed Salad Greens',
      'Cherry Tomatoes',
      'Cucumber',
      'Olive Oil',
      'Lemon Juice',
      'Salt and Pepper',
    ],
    steps: [
      'Peel the banana and break it into chunks.',
      'Add the banana, mixed berries, yogurt, orange juice, and honey to a blender.',
      'Blend until smooth.',
      'Pour into a glass and serve immediately.',
    ],
    duration: 10,
    complexity: Complexity.Simple,
    affordability: Affordability.Affordable,
    isGlutenFree: true,
    isVegan: false,
    isLactoseFree: true,
    isVegetarian: false,
    isFavourite: false,
  ),

  Meal(
    id: '13',
    title: 'Vegan Avocado Toast',
    imageUrl:
        'https://www.veggieinspired.com/wp-content/uploads/2016/12/vegan-avocado-toast-featured.jpg',
    categories: ['c5', 'c6', 'c10'],
    indgredients: [
      '2 Slices Whole Grain Bread',
      '1 Ripe Avocado',
      '1 Tomato',
      'Salt, Pepper, and Lemon Juice',
    ],
    steps: [
      'Toast the whole grain bread slices.',
      'Mash the ripe avocado and spread it evenly on the toasted bread.',
      'Slice the tomato and place it on top of the avocado spread.',
      'Season with salt, pepper, and a squeeze of lemon juice.',
      'Serve immediately and enjoy your vegan avocado toast.',
    ],
    duration: 10,
    complexity: Complexity.Simple,
    affordability: Affordability.Affordable,
    isGlutenFree: false,
    isVegan: true,
    isLactoseFree: true,
    isVegetarian: true,
    isFavourite: false,
  ),

  Meal(
    id: '14',
    title: 'Quinoa Salad',
    imageUrl:
        'https://www.recipetineats.com/tachyon/2021/03/My-Favourite-Quinoa-Salad-5-SQ.jpg',
    categories: ['c5', 'c6', 'c10'],
    indgredients: [
      '1 Cup Quinoa',
      '2 Cups Water',
      '1 Cucumber',
      '1 Bell Pepper',
      '1/2 Red Onion',
      '1/4 Cup Olive Oil',
      '2 Tablespoons Lemon Juice',
      'Salt and Pepper',
    ],
    steps: [
      'Rinse the quinoa under cold water.',
      'Cook the quinoa in water according to package instructions and let it cool.',
      'Chop the cucumber, bell pepper, and red onion.',
      'In a large bowl, combine the cooked quinoa, chopped vegetables, olive oil, lemon juice, salt, and pepper.',
      'Mix well and serve chilled or at room temperature.',
    ],
    duration: 20,
    complexity: Complexity.Simple,
    affordability: Affordability.Affordable,
    isGlutenFree: true,
    isVegan: true,
    isLactoseFree: true,
    isVegetarian: true,
    isFavourite: false,
  ),
  Meal(
    id: '15',
    title: 'Hearty Vegetable Soup',
    imageUrl:
        'https://www.prairiefarms.com/wp-content/uploads/files/2023/entree-Hearty-Beef-Vegetable-Soup.jpg',
    categories: ['c5', 'c6', 'c10'],
    indgredients: [
      '1 Cup Quinoa',
      '2 Cups Water',
      '1 Cucumber',
      '1 Bell Pepper',
      '1/2 Red Onion',
      '1/4 Cup Olive Oil',
      '2 Tablespoons Lemon Juice',
      'Salt and Pepper',
    ],
    steps: [
      'Rinse the quinoa under cold water.',
      'Cook the quinoa in water according to package instructions and let it cool.',
      'Chop the cucumber, bell pepper, and red onion.',
      'In a large bowl, combine the cooked quinoa, chopped vegetables, olive oil, lemon juice, salt, and pepper.',
      'Mix well and serve chilled or at room temperature.',
    ],
    duration: 20,
    complexity: Complexity.Simple,
    affordability: Affordability.Affordable,
    isGlutenFree: true,
    isVegan: true,
    isLactoseFree: true,
    isVegetarian: true,
    isFavourite: false,
  ),

  Meal(
    id: '16',
    title: 'Spicy Tofu Stir-Fry',
    imageUrl:
        'https://www.simplyrecipes.com/thmb/eSjn6vsdKpQIdrD4msJcO41Wm84=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Spicy-Tofu-Stirfry-LEAD-3-3da17681605c41688be8742e045f71f5.jpg',
    categories: ['c5', 'c6', 'c10'],
    indgredients: [
      '200g Firm Tofu',
      '1 Bell Pepper',
      '1 Broccoli Floret',
      '2 Carrots',
      '2 Tablespoons Soy Sauce',
      '1 Teaspoon Chili Sauce',
      '2 Cloves Garlic',
      '1 Tablespoon Vegetable Oil',
    ],
    steps: [
      'Press the firm tofu to remove excess moisture and cut it into cubes.',
      'Chop the bell pepper, broccoli florets, and carrots.',
      'Heat vegetable oil in a pan over medium heat.',
      'Add minced garlic and sauté until fragrant.',
      'Add tofu cubes and cook until golden brown on all sides.',
      'Add chopped vegetables and stir-fry for a few minutes.',
      'Add soy sauce and chili sauce, and cook for another 2-3 minutes.',
      'Serve hot with rice or noodles.',
    ],
    duration: 25,
    complexity: Complexity.Simple,
    affordability: Affordability.Affordable,
    isGlutenFree: true,
    isVegan: true,
    isLactoseFree: true,
    isVegetarian: true,
    isFavourite: false,
  ),

  Meal(
    id: '17',
    title: 'Avocado Salad',
    imageUrl:
        'https://cdn.loveandlemons.com/wp-content/uploads/2024/07/avocado-salad-500x500.jpg',
    categories: ['c5', 'c6', 'c10'],
    indgredients: [
      '2 Avocados',
      '1 Tomato',
      '1/2 Red Onion',
      '1/4 Cup Cilantro',
      '2 Tablespoons Lime Juice',
      'Salt and Pepper',
    ],
    steps: [
      'Cut the avocados in half, remove the pit, and scoop the flesh into a bowl.',
      'Chop the tomato, red onion, and cilantro.',
      'Add the chopped vegetables to the bowl with avocado.',
      'Add lime juice, salt, and pepper.',
      'Mix gently to combine all ingredients.',
      'Serve immediately or chill before serving.',
    ],
    duration: 15,
    complexity: Complexity.Simple,
    affordability: Affordability.Affordable,
    isGlutenFree: true,
    isVegan: true,
    isLactoseFree: true,
    isVegetarian: true,
    isFavourite: false,
  ),

  Meal(
    id: '18',
    title: 'Banana Pancakes',
    imageUrl:
        'https://www.allrecipes.com/thmb/6x0Lw9L4MEU8INHnK4tXGRV9XWI=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20334-banana-pancakes-i-DDMFS-4x3-9f291f03044247d48c9ec26917952402.jpg',
    categories: ['c7', 'c10'],
    indgredients: [
      '1 Banana',
      '1 Cup Flour',
      '1 Cup Milk',
      '1 Egg',
      '1 Tablespoon Sugar',
      '1 Teaspoon Baking Powder',
      'Pinch of Salt',
    ],
    steps: [
      'Mash the banana in a bowl.',
      'Add flour, milk, egg, sugar, baking powder, and salt to the mashed banana.',
      'Mix until smooth batter forms.',
      'Heat a non-stick pan over medium heat and pour batter to form pancakes.',
      'Cook until bubbles form on the surface, then flip and cook until golden brown.',
      'Serve warm with syrup or toppings of choice.',
    ],
    duration: 20,
    complexity: Complexity.Simple,
    affordability: Affordability.Affordable,
    isGlutenFree: false,
    isVegan: false,
    isLactoseFree: false,
    isVegetarian: true,
    isFavourite: false,
  ),

  Meal(
    id: '19',
    title: 'Tomato Basil Soup',
    imageUrl:
        'https://therecipecritic.com/wp-content/uploads/2019/10/CE584C80-05AB-4560-9C2A-9D9F059EC932.jpeg',
    categories: ['c1', 'c5', 'c10'],
    indgredients: [
      '6 Tomatoes',
      '1 Onion',
      '2 Cloves Garlic',
      '1 Cup Fresh Basil Leaves',
      '2 Cups Vegetable Broth',
      '1/2 Cup Cream',
      'Salt and Pepper',
    ],
    steps: [
      'Chop the tomatoes, onion, and garlic.',
      'Sauté the onion and garlic in a pot until translucent.',
      'Add chopped tomatoes and cook until soft.',
      'Add vegetable broth and bring to a boil.',
      'Simmer for 20 minutes.',
      'Add fresh basil leaves and blend the soup until smooth.',
      'Stir in cream and season with salt and pepper.',
      'Serve hot with a garnish of basil leaves.',
    ],
    duration: 30,
    complexity: Complexity.Simple,
    affordability: Affordability.Affordable,
    isGlutenFree: true,
    isVegan: false,
    isLactoseFree: false,
    isVegetarian: true,
    isFavourite: false,
  ),

  Meal(
    id: '20',
    title: 'Greek Yogurt Parfait',
    imageUrl: 
        'https://foolproofliving.com/wp-content/uploads/2017/12/Greek-Yogurt-Parfait-Recipe.jpg',
    categories: ['c7', 'c10'],
    indgredients: [
      '1 Cup Greek Yogurt',
      '1/2 Cup Granola',
      '1/2 Cup Mixed Berries',
      '1 Tablespoon Honey',
    ],
    steps: [
      'Layer Greek yogurt, granola, and mixed berries in a glass or bowl.',
      'Drizzle honey on top.',
      'Repeat layers if desired.',
      'Serve immediately or chill before serving.',
    ],
    duration: 10,
    complexity: Complexity.Simple,
    affordability: Affordability.Affordable,
    isGlutenFree: true,
    isVegan: false,
    isLactoseFree: false,
    isVegetarian: true,
    isFavourite: false,
  ),
];
// Add more meals as needed
